# Generated by Django 4.1.3 on 2022-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
